API/API/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apis.urls'))
]

API2/API2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apis2.urls'))
]

IWFF/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('carro/', include('carro.urls')),
    path('accounts/',include('django.contrib.auth.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from . import views
from django.urls import path
app_name="carro"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name="agregar"),
    path('agregar_home/<int:producto_id>/', views.agregar_producto_home, name="agregar_home"),
    path('agregar_cuerda/<int:producto_id>/', views.agregar_producto_cuerda, name="agregar_cuerda"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name="eliminar"), 
    path('restar/<int:producto_id>/', views.restar_producto, name="restar"), 
    path('limpiar/', views.limpiar_carro, name="limpiar"), 
    path('limpiar_producto/', views.limpiar_carro_producto, name="limpiar_producto"), 
]

core/urls.py
from collections import namedtuple
from django.urls import path
from django.urls.conf import include
from requests.models import parse_header_links
from .views import *    
from django.contrib import admin
from rest_framework import routers


#Registros de las apis 
router = routers.DefaultRouter()
router.register('producto', ProductoViewset)
router.register('familia', FamiliaViewset)
router.register('categoria',CategoriaViewset)
router.register('proveedor',ProveedorViewset)






urlpatterns = [
    path('',home, name='home'), 
    #contacto
    path('contacto/', contacto, name="contacto"),
    #producto
    path('agregarproducto/', agregar_producto, name="agregar_producto"),
    path('listarproducto/', listar_productos, name="listar_producto"),
    path('api/producto/<id>/', modificar_producto, name="modificar_producto"),
    path('eliminarproducto/<id>/', eliminar_producto, name="eliminar_producto"),
    #registro
    path('register/', register, name="register"),
    #Categoria
    path('listar_categoria/', listar_categoria, name='listar_categoria' ),
    path('nueva_categoria/', nueva_categoria, name='nueva_categoria'),
    path('modificarcategoria/<id>/', modificar_categoria, name="modificar_categoria"),
    path('eliminarcategoria/<id>/', eliminar_categoria, name="eliminar_categoria"),
    #familia
    path('listar_familias/', listar_familias, name='listar_familias' ),
    path('nueva_familia/', nueva_familia, name='nueva_familia'),
    path('modificarfamilia/<id>/', modificar_familia, name="modificar_familia"),
    path('eliminarfamilia/<id>/', eliminar_familia, name="eliminar_familia"),
    #Proveedor
    path('listar_proveedor/', listar_proveedor, name='listar_proveedor' ),
    path('nuevo_proveedor/', nuevo_proveedor, name='nuevo_proveedor'),
    path('modificarproveedor/<id>/', modificar_proveedor, name="modificar_proveedor"),
    path('eliminarproveedor/<id>/', eliminar_proveedor, name="eliminar_proveedor"),
    #lista de los productos
    path('prodCuerdas/', prodCuerdas, name="prodCuerdas"),
    #carrito
    path('cart/', cart, name="cart"),
    #filtros
    path('prodPianos/', prodPianos, name="prodPianos"),
    path('prodBaterias/', prodBaterias, name="prodBaterias"),
    path('prodAmplificador/', prodAmplificador, name="prodAmplificador"),
    path('accesorios/', accesorios, name="accesorios"),
    #APIS
    path('api/', include(router.urls)),
    path('api2/', include(router.urls)),
    #TBK
    #path('tbk/',tbk,name='tbk'),
    path('tbkRes/', statusTrx, name="tbkRes"),
]

core/models.py
from django.db import models
from django.db.models.base import ModelState
from django.db.models.expressions import Case
from django.db.models.fields import BooleanField, CharField, NullBooleanField
from django.contrib.auth.models import User
from datetime import date,datetime
from django.utils.text import slugify
from API.apis.models import categoria
from API2.apis2.models import proveedor
#Create your models here


class familia(models.Model):
    nombre = models.CharField(max_length=50)
    categoria = models.ForeignKey(categoria, on_delete=models.PROTECT)

    def __str__(self):
        return self.nombre



class producto(models.Model):
    nombre = models.CharField(max_length=30)
    descripcion = models.TextField(max_length=300)
    precio = models.IntegerField() 
    familia = models.ForeignKey(familia, on_delete=models.PROTECT)
    stock = models.IntegerField()
    proveedor = models.ForeignKey(proveedor, on_delete=models.PROTECT)
    imagen = models.ImageField(upload_to='productos', null=True)
    oferta = models.BooleanField(default='0', null=False)

    def __str__(self):
        return self.nombre

class cargo(models.Model):
    nombre = models.CharField(max_length=20)
    descripcio = models.TextField()

class persona(models.Model):
    rut = models.IntegerField()
    nombre = models.TextField()
    telefono = models.IntegerField()
    cargo = models.ForeignKey(cargo, on_delete=models.PROTECT)
    User = models.ForeignKey(User, on_delete=models.CASCADE,null=False,default=None)
    def __str__(self):
        return self.nombre

opciones_consultas = [

    [0, 'Consulta'],
    [1, 'Reclamo'],
    [2, 'Sugerencia'],
    [3, 'Felicitaciones'],
    [4, 'Solicitud de Proveedor']]

class contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre

class factura(models.Model): 
    fecha = models.DateField(default=datetime.today)
    producto = models.ForeignKey(producto, on_delete=models.CASCADE)
    canitdad_producto = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return self.id

class boleta(models.Model):
    fecha = models.DateField(default=datetime.today)
    producto = models.ForeignKey(producto, on_delete=models.CASCADE)
    canitdad_producto = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return self.id

class cliente(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    nombre = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.nombre

class orden(models.Model):
    cliente = models.ForeignKey(cliente, on_delete=models.SET_NULL, null=True, blank=True)
    orden_fecha = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaccion_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        ordenitems = self.ordenitem_set.all()
        total = sum([item.get_total for item in ordenitems])
        return total
    
    @property
    def get_cart_items(self):
        ordenitems = self.ordenitem_set.all()
        total = sum([item.cantidad for item in ordenitems])
        return total

class ordenItem(models.Model):
    producto = models.ForeignKey(producto, on_delete=models.SET_NULL, null=True)
    orden = models.ForeignKey(orden, on_delete=models.SET_NULL, null=True)
    cantidad = models.IntegerField(default=0, null=True, blank=True)
    fecha_agregada = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.producto.precio * self.cantidad
        return total

class direccion_envio(models.Model):
    cliente = models.ForeignKey(cliente, on_delete=models.SET_NULL, null=True)
    orden = models.ForeignKey(orden, on_delete=models.SET_NULL, null=True)
    direccion = models.CharField(max_length=200, null=False)
    ciudad = models.CharField(max_length=200, null=False)
    Region = models.CharField(max_length=200, null=False)
    codigo_postal = models.CharField(max_length=200, null=False)
    fecha_agregada = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.direccion

core/forms.py
from typing import ClassVar
from django import forms
from django.contrib import auth
from django.db import models
from django.db.models import fields
from django.forms import widgets    
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from API.apis.models import categoria
from API2.apis2.models import proveedor

class ContactoForms(forms.ModelForm):
    
    class Meta:
        model = contacto
        #Fiedls detalla todos los datos para el formulario como se necesitan todos se usa __all__
        fields = '__all__'



class AgregarProductoForms(forms.ModelForm):
    class Meta:
        model = producto
        fields = '__all__'

class AgregarFamiliaForms(forms.ModelForm):
    class Meta:
        model = familia
        fields = '__all__'

class AgregarCategoriaForms(forms.ModelForm):
    class Meta:
        model = categoria
        fields = '__all__'

class RegistroForms(UserCreationForm):

    pass


class PersonaFoms(forms.ModelForm):
    class Meta:
        model = persona
        fields = '__all__'

class AgregarProveedorForms(forms.ModelForm):
    class Meta:
        model = proveedor
        fields = '__all__'

core/templates/core/Contacto.html
{% extends 'core/base.html' %}

{% block contenido %}

{% load crispy_forms_tags %}

<div class="col-12 col-md-6 offset-md-3 ">
    <div class=" row p-3 mb-2 ">
            <div class="card">
                <div class="card-body">
                    <h2>Contacto</h2>
            
            
                    <form action="" method="POST">
            
                        {% csrf_token %}
                        {{ form | crispy }}
                        <br>
                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" id="btnCancelar" class="btn btn-secondary">
                            &nbsp;
                            <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
                    
                        </div>
                    
                    </form>
                    {{mensaje}}
            
                </div>
            </div>
        </div>
</div>



{% endblock %}

core/templates/core/accesorios.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}
{% block contenido %}

<h2 style="color: aliceblue; font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;" class="text-center">Accesorios</h2>
{% load humanize %}
<div class="container">
      <div class="row text-center">
        {% for p in producto %}
          {% if p.oferta == 1 %}
          {% if p.stock %}

          <div class="col-md-4 pb-1 pb-md-0">
            <div class="card">
              <div>
                <img src="{{ p.imagen }}" class="card-img-top" alt="imagen">
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ p.nombre }}</h5>
                <p class="card-text">{{ p.descripcion }}</p>
                <p class="card-text">${{ p.precio | intcomma}}</p>
                <a href="#" class="btn btn-primary">Añadir al carrito</a>
              </div>
            </div>        
          </div>
          {% endif %}
          {% endif %}
        {% endfor %}
      </div>
    </div>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MusicPRO</title>
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
  <script type="text/javascript">
    var user = '{{request.user}}'

    function getToken(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
    var csrftoken = getToken('csrftoken')

  </script>
  {% block css %}
  {% endblock %}

  {% block head %}
  {% endblock %}
</head>

<body id="intro" class="bg-image shadow-2-strong">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/img/LOGITO2.png' %}" height="60"
        alt="logo"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Inicio</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Categorias
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'prodCuerdas' %}">Instrumentos de cuerdas</a>
            <a class="dropdown-item" href="{% url 'prodPianos' %}">Pianos</a>
            <a class="dropdown-item" href="{% url 'prodBaterias' %}">Baterias</a>
            <a class="dropdown-item" href="{% url 'prodAmplificador' %}">Amplificadores</a>
            <a class="dropdown-item" href="{% url 'accesorios' %}">Accesorios varios</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contacto' %}">Contacto</a>
        </li>
        {% if perms.core.view_producto %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Administrar
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'listar_producto' %}">Productos</a>
            <a class="dropdown-item" href="{% url 'listar_categoria' %}">Categorías</a>
            <a class="dropdown-item" href="{% url 'listar_familias' %}">Familias</a>
            <a class="dropdown-item" href="{% url 'listar_proveedor' %}">Proveedores</a>
          </div>
        </li>


        {% endif %}



        
      </ul>
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <a class="nav-link" href="{% url 'cart' %}">
          <img id="cart-icon" src="{% static 'images/cart.png' %}" alt="carrito" />
        </a>
        <p id="cart-total">{{importe_cant_carro}}</p>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Usuario: {{ user.username |title }}</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Iniciar Sesion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
        </li>
        {% endif %}
        
      </ul>
      
    </div>
  </nav>
  {% block jumbotron %}

  {% endblock %}

  <div class="contenedorprincipal d-flex">
    {% block contenido %}

    {% endblock %}
  </div>

  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
    integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
    crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/moneda.js' %}"></script>
  <script src="{% static 'js/cart.js' %}"></script>

  {% block scripts %}
  {% endblock %}




  {% if messages %}
  {% for m in messages %}
  <script>
    Swal.fire(

      "",
      "{{m}}",
      "success"
    )


  </script>
  {% endfor %}
  {% endif %}

  <footer class="text-center text-lg-start">
    <div class="container d-flex justify-content-center py-5">
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2">
        <i class="fab fa-facebook-f"></i>
      </button>
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2">
        <i class="fab fa-youtube"></i>
      </button>
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2">
        <i class="fab fa-instagram"></i>
      </button>
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2">
        <i class="fab fa-twitter"></i>
      </button>
    </div>
    <div class="text-center text-white p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2021
      <a class="text-white" href="{% url 'home' %}">MusicPRO</a>
    </div>
  </footer>
</body>

</html>

core/templates/core/cart.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}
{% block contenido %}

<div class="carro.css/row">
    <div class="carro.css/col-lg-12">
        <div class="box-element">
            <table class="table">
                <tr>
                    <th><h5>Cantidad Total: <strong>{{importe_cant_carro | intcomma}}</strong></h5></th>
                    <th><h5>Precio Total: <strong>$ {{importe_total_carro | intcomma}}</strong></h5></th>
                    <th>
                        <a style="float:right; margin:5px;" class="btn btn-success" href="{% url "carro:limpiar" %}">Limpiar carrito
                        </a>
                    </th>
                </tr>
            </table>
        </div>
    </div>
    <br>
    <div class="box-element">
        <div class="cart-row">
            <div style="flex:2"></div>
            <div style="flex:2"><strong>Item</strong></div>
            <div style="flex:1"><strong>Cantidad</strong></div>
            <div style="flex:1"><strong>Total</strong></div>
        </div>

        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <div class="cart-row">
                    <div style="flex:2">
                    <img class="row-image" src="{{value.imagen}}"></div>
                    <div style="flex:2">{{value.nombre}}</div>
                    <div style="flex:1">
                        <p class="quantity">{{value.cantidad}}</p>
                        <div class="quantity">
                            <a href="{% url 'carro:agregar' value.producto_id %}"><img class="chg-quantity" src="{% static 'images/arrow-up.png' %}"></a>
                            <a href="{% url 'carro:restar' value.producto_id %}"><img class="chg-quantity" src="{% static 'images/arrow-down.png' %}"></a>
                        </div>
                        <a style="float: right; padding-right: 180px;" href="{% url 'carro:eliminar' value.producto_id %}"><img class="chg-quantity" src="{% static 'images/basurita.png' %}"></a>
                    </div>
                    <div style="flex:1">$ {{value.precio | intcomma}}</div>
                </tr>
                </div>
            {% endfor %}
        {% else %}
            <tr>
              <td colspan="3">
                <div class="alert alert-danger text-center">
                  Sin productos
                </div>
              </td>
            </tr>
        {% endif %}
        {{mensaje}}
        <form method="POST" enctype="multipart/form-data" action="{{resultado.url}}?token_ws={{resultado.token}}">
            <input type="hidden" name="precio_total" value="{{importe_total_carro}}">
            <input type="hidden" name="token_ws" value="{{resultado.token}}" disabled>
            <input type="submit"  value="Pagar" class="btn btn-success">   
        </form>
    </div>
</div>

{% endblock %}

core/templates/core/checkout.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}
{% block contenido %}

<div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
                <form id="form">
                    <div id="user-info">
                        <div class="form-field">
                            <input required class="form-control" type="text" name="nombre" placeholder="nombre...">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="email" name="email" placeholder="correo electronico...">
                        </div>
                        
                    </div>
                    <div id="shipping-info">
                        <div class="form-field">
                            <input class="form-control" type="text" name="direccion" placeholder="Direccion...">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="ciudad" placeholder="Ciudad...">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="region" placeholder="Region...">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="codigoPostal" placeholder="Codigo postal...">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="pais" placeholder="Pais...">
                        </div>
                    </div>
                    <hr>
                    <input id="form-button" class="btn btn-succes btn-block" type="submit" value="continuar con la compra">
                </form>
			</div>
            <br>
            <div class="box-element hidden" id="payment-info">
                <small>Paypal Options</small>
            </div>
		</div>

		<div class="col-lg-6">
			<div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190;Volver al carrito</a>
                <hr>
                <h3>Sumativa de orden</h3>
                <hr>
                {% for item in items %}
                <div class="cart-row">
                    <div style="flex:2"><img class='row-image' src="{{item.producto.imagen.url}}"></div>
                    <div style="flex:2"><p>{{item.producto.nombre}}</p></div>
                    <div style="flex:1"><p>${{item.producto.precio}}</p></div>
                    <div style="flex:1"><p>{{item.cantidad}}</p></div>
                </div>
                {% endfor %}

                <h5>Cantidad: {{Orden.get_cart_items}}</h5>
                <h5>Total: {{Orden.get_cart_total}}</h5>
			</div>
		</div>
	</div>

{% endblock %}

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}

{% block jumbotron %}

<div class="partejumbo">
  <div class="jumbotron">
    <h1 class="titulo">Buenas Noticias!</h1>
    <p class="lead">Ya se ha podido implementar el sistema de pago WebPay en nuestro sitio web!.</p>
    <hr class="my-4">
    <p class="medio">Éste sistema les permitirá realizar sus pagos vía débito y transferencia bancaria.</p>
    <p class="lead"> <a class="btn btn-lg" href="#" role="button">Leer Más</a> </p>
  </div>
</div>

{% endblock %}

{% block contenido %}

  <div class="container-fluid justify-content-center">
      <h2 style="color: aliceblue;" class="text-center">PRODUCTOS RECOMENDADOS</h2>
    <hr>
    <div class="row row-cols-4 justify-content-around">

      {% for p in listado %}
          {% if p.oferta %}
          {% if p.stock %}
          <div id="productitoseparado" class="">
            <img src="{{ p.imagen }}" class="thumbnail" alt="imagen">
            <div class="box-element product">
              <h2 id="nombreproducto">
                <strong>{{ p.nombre }}</strong>
              </h2>
              <hr>
              <h5 id="marcaproducto">
                {{ p.descripcion }}
              </h5>
                {% if p.precio > 0 %}
                <h1 id="precioproducto" class="d-flex justify-content-end align-items-center">
                  ${{ p.precio | intcomma}}
                </h1>
                <br>
                <div class="d-flex justify-content-center">
                  <a href="{% url 'carro:agregar' p.id %}" class="btn btn-outline-primary text-center">
                    Añadir al carrito
                  </a>
                </div>
                {% else %}
                <p class="card-text">
                  No tiene precio</p>
                {% endif %}
            </div>
          </div>
          {% endif %}
        {% endif %}
      {% endfor %}
    </div>
  </div>
    

{% endblock %}

core/templates/core/prodAmplificador.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}
{% block contenido %}

<h2 style="color: aliceblue; font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;" class="text-center">Amplificador</h2>
{% load humanize %}
<div class="container">
      <div class="row text-center">
        {% for p in producto %}
          {% if p.oferta == 1 %}
          {% if p.stock %}
          <div class="col-md-4 pb-1 pb-md-0">
            <div class="card">
              <div>
                <img src="{{ p.imagen }}" class="card-img-top" alt="imagen">
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ p.nombre }}</h5>
                <p class="card-text">{{ p.descripcion }}</p>
                <p class="card-text">${{ p.precio | intcomma}}</p>
                <a href="#" class="btn btn-primary">Añadir al carrito</a>
              </div>
            </div>        
          </div>
          {% endif %}
          {% endif %}
        {% endfor %}
      </div>
    </div>
{% endblock %}

core/templates/core/prodCuerdas.html
{% extends 'core/base.html' %}
{% load static %}
{% block contenido %}

<h2 style="color: azure; font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;" class="text-center" >Instrumentos de cuerdas</h2>
{% load humanize %}
<div class="container">
      <div class="row text-center">
        {% for p in producto %}
        {% if p.stock %}
              <div class="col-md-4 pb-1 pb-md-0" style="width:285px; margin-top:6px;">
                <div class="card">
                    <div>
                      <img src="{{ p.imagen }}" class="card-img-top" alt="imagen">
                    </div>
                  <div class="card-body">
                    <h5 class="card-title">{{ p.nombre }}</h5>
                    <p class="card-text">{{ p.descripcion }}</p>
                    <p class="card-text">${{ p.precio | intcomma }}</p>
                    <a href="{% url 'carro:agregar_cuerda' p.id %}" class="btn btn-primary btn-outline-secondary add-btn update-cart">Añadir al carrito</a>
                  </div>
                </div>        
            </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}